config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :billings
  resources :client_payment_methods
  resources :clients
  resources :payment_methods

  get '/clients/:id/payment_method', to: 'clients#edit_payment_method', as: :edit_client_payment
  post '/clients/:id/payment_method', to: 'clients#update_payment_method', as: :update_client_payment
  patch '/clients/:id/payment_method', to: 'clients#update_payment_method'

  get 'billings_of_the_day', to: 'billings#billings_of_the_day', as: :billings_of_the_day

  root to: 'billings#index'
end

app/models/payment_method.rb
# == Schema Information
#
# Table name: payment_methods
#
#  id                   :bigint           not null, primary key
#  name                 :string
#  message              :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
class PaymentMethod < ApplicationRecord
  ##
  # Constants

  ##
  # Attributes

  ##
  # Enums

  ##
  # Behaviours

  ##
  # Relationships

  ##
  # Validations
  validates_presence_of :name, :message

  ##
  # Callbacks

  ##
  # Scopes

  ##
  # Class Methods

  ##
  # Instance Methods

end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!

  # GET /payment_methods or /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all
  end

  # GET /payment_methods/1 or /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods or /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @payment_method, notice: "Payment method was successfully created." }
        format.json { render :show, status: :created, location: @payment_method }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1 or /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to @payment_method, notice: "Payment method was successfully updated." }
        format.json { render :show, status: :ok, location: @payment_method }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1 or /payment_methods/1.json
  def destroy
    @payment_method.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: "Payment method was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = PaymentMethod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_method_params
      params.require(:payment_method).permit(:name, :message)
    end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@payment_method) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: 'Nome'
    = f.input :message, label: 'Mensagem de feedback'

  %br

  .form-actions
    = f.submit 'Salvar método de pagamento', class: 'btn btn-success'

  %br

app/views/payment_methods/edit.html.haml
%h1 Editar Método de pagamento

= render 'form'

= link_to 'Voltar', payment_methods_path, class: 'btn btn-light'

app/views/payment_methods/index.html.haml
%h1 Métodos de pagamento

.table-responsive
  %table.table.align-middle
    %thead
      %tr
        %th Nome
        %th Mensagem de cobrança
        %th
        %th
        %th

    %tbody
      - @payment_methods.each do |payment_method|
        %tr
          %td= payment_method.name
          %td= payment_method.message
          %td= link_to 'Ver', payment_method, class: 'text-success'
          %td= link_to 'Editar', edit_payment_method_path(payment_method), class: 'text-info'
          %td= link_to 'Excluir', payment_method, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'text-danger'

%br

= link_to 'Novo método de pagamento', new_payment_method_path, class: 'btn btn-secondary'

app/views/payment_methods/new.html.haml
%h1 Novo método de pagamento

= render 'form'

= link_to 'Voltar', payment_methods_path, class: 'btn btn-light'

app/views/payment_methods/show.html.haml
%p#notice= notice

.card{:style => "width: 400px; max-width: 100%"}
  .card-body
    %h5.card-title Método de pagamento
    %hr

    %text Nome:
    %strong= @payment_method.name
    %br
    %text Mensagem de feedback:
    %strong= @payment_method.message
  .card-footer
    = link_to 'Voltar', payment_methods_path, class: 'btn btn-light'
    = link_to 'Editar', edit_payment_method_path(@payment_method), class: 'btn btn-primary float-right'