config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :billings
  resources :client_payment_methods
  resources :clients
  resources :payment_methods

  get '/clients/:id/payment_method', to: 'clients#edit_payment_method', as: :edit_client_payment
  post '/clients/:id/payment_method', to: 'clients#update_payment_method', as: :update_client_payment
  patch '/clients/:id/payment_method', to: 'clients#update_payment_method'

  get 'billings_of_the_day', to: 'billings#billings_of_the_day', as: :billings_of_the_day

  root to: 'billings#index'
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id                   :bigint           not null, primary key
#  name                 :string
#  last_billed_at       :date
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
class Client < ApplicationRecord
  ##
  # Constants

  ##
  # Attributes

  ##
  # Enums

  ##
  # Behaviours

  ##
  # Relationships
  has_many :billings
  has_one :client_payment_method

  ##
  # Validations
  validates_presence_of :name, :billing_day

  ##
  # Callbacks

  ##
  # Scopes
  scope :ready_to_bill, -> { where('clients.billing_day <= ?', Date.today.day) }

  ##
  # Class Methods

  ##
  # Instance Methods
  def payment_method_name
    return 'Não há nenhum método de pagamento associado à este cliente' unless self.client_payment_method.present?
    self.client_payment_method.payment_method.name
  end

  def payment_method_message
    return 'Não há nenhum método de pagamento associado à este cliente' unless self.client_payment_method.present?
    self.client_payment_method.payment_method.message
  end

  def bill!
    BillingService.new(self).make_bill
  end

  def billed?
    self.last_billed_at&.month.eql? Date.today.month
  end

  def ready_to_bill?
    self.billing_day <= Date.today.day && self.client_payment_method.present?
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy edit_payment_method update_payment_method ]
  before_action :set_payment_method, only: %i[ edit_payment_method update_payment_method ]
  before_action :authenticate_admin!

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def edit_payment_method
  end

  def update_payment_method
    @payment_method.payment_method_id = params[:client_payment_method][:payment_method_id]

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    def set_payment_method
      @payment_method = @client.client_payment_method
      @payment_method ||= ClientPaymentMethod.new(client: @client)
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :last_billed_at, :billing_day, :client_payment_method)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@client) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: 'Nome'
    = f.input :billing_day, label: 'Dia de cobrar'

  %br

  .form-actions
    = f.submit 'Salvar cliente', class: 'btn btn-success'

  %br

app/views/clients/edit.html.haml
%h1 Editar cliente

= render 'form'

= link_to 'Voltar', clients_path, class: 'btn btn-light'

app/views/clients/edit_payment_method.html.haml
%h1 Método de pagamento do cliente

%hr

%p
  Cliente:
  = @client.name.capitalize

%br
%br

= simple_form_for @payment_method, url: :update_client_payment do |f|
  = f.association :payment_method, label: 'Método de pagamento'

  %br

  = f.submit "Salvar", class: 'btn btn-success'

app/views/clients/index.html.haml
%h1 Clientes

.table-responsive
  %table.table.align-middle
    %thead
      %tr
        %th Nome
        %th Cobrado em
        %th Dia de cobrança
        %th
        %th
        %th

    %tbody
      - @clients.each do |client|
        %tr
          %td= client.name
          %td= format_date(client.last_billed_at)
          %td= client.billing_day
          %td= link_to 'Ver', client, class: 'text-success'
          %td= link_to 'Editar', edit_client_path(client), class: 'text-info'
          %td= link_to 'Excluir', client, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'text-danger'

%br

= link_to 'Novo Cliente', new_client_path, class: 'btn btn-secondary'

app/views/clients/new.html.haml
%h1 Novo Cliente

= render 'form'

= link_to 'Voltar', clients_path, class: 'btn btn-light'

app/views/clients/show.html.haml
%p#notice= notice

.card{:style => "width: 400px; max-width: 100%"}
  .card-body
    %h5.card-title Cliente
    %hr

    %text Nome:
    %strong= @client.name
    %br
    %text Cobrança mais recente:
    %strong= format_date(@client.last_billed_at)
    %br
    %text Dia de cobrança:
    %strong= @client.billing_day
    %br
    %text Forma de pagamento:
    %strong= @client.payment_method_name
    %br
    %br
    = link_to 'Forma de pagamento', edit_client_payment_path(@client), class: 'btn btn-secondary'
  .card-footer
    = link_to 'Voltar', clients_path, class: 'btn btn-light'
    = link_to 'Editar', edit_client_path(@client), class: 'btn btn-primary float-right'