config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :billings
  resources :client_payment_methods
  resources :clients
  resources :payment_methods

  get '/clients/:id/payment_method', to: 'clients#edit_payment_method', as: :edit_client_payment
  post '/clients/:id/payment_method', to: 'clients#update_payment_method', as: :update_client_payment
  patch '/clients/:id/payment_method', to: 'clients#update_payment_method'

  get 'billings_of_the_day', to: 'billings#billings_of_the_day', as: :billings_of_the_day

  root to: 'billings#index'
end

app/models/billing.rb
# == Schema Information
#
# Table name: billings
#
#  id                   :bigint           not null, primary key
#  accounted_at         :date
#  client_id            :integer          not null
#  payment_method_id    :integer          not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
class Billing < ApplicationRecord
  ##
  # Constants

  ##
  # Attributes

  ##
  # Enums

  ##
  # Behaviours

  ##
  # Relationships
  belongs_to :client
  belongs_to :payment_method

  ##
  # Validations

  ##
  # Callbacks
  after_create :set_accounted_at

  ##
  # Scopes
  scope :today, -> { where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day) }

  ##
  # Class Methods

  ##
  # Instance Methods
  def set_accounted_at
    self.update(accounted_at: Date.today)
  end
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_action :set_billing, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!

  # GET /billings or /billings.json
  def index
    @billings = Billing.all
  end

  def billings_of_the_day
    @billings = Billing.today
  end

  # GET /billings/1 or /billings/1.json
  def show
  end

  # GET /billings/new
  def new
    @billing = Billing.new
  end

  # GET /billings/1/edit
  def edit
  end

  # POST /billings or /billings.json
  def create
    client = Client.find_by_id(billing_params[:client_id].to_i)
    if !client.billed? && client.ready_to_bill?
      @billing = BillingService.new(client).make_bill
    else
      @billing = "Falha ao processar o pagamento. O cliente #{client.name} já foi cobrado ou não está dentro da data prevista para pagamento este mês"
    end

    respond_to do |format|
      format.html { redirect_to billings_path, notice: @billing }
    end
  end

  # PATCH/PUT /billings/1 or /billings/1.json
  def update
    respond_to do |format|
      if @billing.update(billing_params)
        format.html { redirect_to @billing, notice: "Billing was successfully updated." }
        format.json { render :show, status: :ok, location: @billing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billings/1 or /billings/1.json
  def destroy
    @billing.destroy
    respond_to do |format|
      format.html { redirect_to billings_url, notice: "Billing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_billing
      @billing = Billing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def billing_params
      params.require(:billing).permit(:accounted_at, :client_id, :payment_method_id)
    end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/views/billings/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@billing) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :client, label: 'Cliente'

  %br

  .form-actions
    = f.submit 'Realizar cobrança', class: 'btn btn-success'

  %br  	

app/views/billings/billings_of_the_day.html.haml
%p#notice= notice

%h1 Cobranças do dia

.table-responsive
  %table.table.align-middle
    %thead
      %tr
        %th Data da cobrança
        %th Cliente
        %th Forma de pagamento
        %th
        %th
        %th

    %tbody
      - @billings.each do |billing|
        %tr
          %td= format_date(billing.accounted_at)
          %td= link_to billing.client.name.capitalize, client_path(billing.client)
          %td= billing.payment_method.name
          %td= link_to 'Ver', billing, class: 'text-success'
          %td= link_to 'Editar', edit_billing_path(billing), class: 'text-info'
          %td= link_to 'Excluir', billing, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'text-danger'

%br

= link_to 'Fazer cobrança', new_billing_path, class: 'btn btn-secondary'

app/views/billings/edit.html.haml
%h1 Editar Cobrança

= render 'form'

= link_to 'Voltar', billings_path, class: 'btn btn-light'

app/views/billings/index.html.haml
%p#notice= notice

%h1 Todas as cobranças

.table-responsive
  %table.table.align-middle
    %thead
      %tr
        %th Data da cobrança
        %th Cliente
        %th Forma de pagamento
        %th
        %th
        %th

    %tbody
      - @billings.each do |billing|
        %tr
          %td= format_date(billing.accounted_at)
          %td= link_to billing.client.name.capitalize, client_path(billing.client)
          %td= billing.payment_method.name
          %td= link_to 'Ver', billing, class: 'text-success'
          %td= link_to 'Editar', edit_billing_path(billing), class: 'text-info'
          %td= link_to 'Excluir', billing, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'text-danger'

%br

= link_to 'Fazer cobrança', new_billing_path, class: 'btn btn-secondary'

app/views/billings/new.html.haml
%h1 Nova cobrança

= render 'form'

= link_to 'Voltar', billings_path, class: 'btn btn-light'

app/views/billings/show.html.haml
%p#notice= notice

.card{:style => "width: 400px; max-width: 100%"}
  .card-body
    %h5.card-title Cobrança
    %hr

    %text Cobrado em:
    %strong= format_date(@billing.accounted_at)
    %br
    %text Cliente:
    %strong= link_to @billing.client.name.capitalize, client_path(@billing.client)
    %br
    %text Forma de pagamento:
    %strong= @billing.payment_method.name
    %br
  .card-footer
    = link_to 'Voltar', billings_path, class: 'btn btn-light'
    = link_to 'Editar', edit_billing_path(@billing), class: 'btn btn-primary float-right'