config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :billings
  resources :client_payment_methods
  resources :clients
  resources :payment_methods

  get '/clients/:id/payment_method', to: 'clients#edit_payment_method', as: :edit_client_payment
  post '/clients/:id/payment_method', to: 'clients#update_payment_method', as: :update_client_payment
  patch '/clients/:id/payment_method', to: 'clients#update_payment_method'

  get 'billings_of_the_day', to: 'billings#billings_of_the_day', as: :billings_of_the_day

  root to: 'billings#index'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BillingProject
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg
      .container-fluid
        %a{:href => "/"}
          %img{src: 'https://pa1.narvii.com/6507/3b12357d80b8425c198926c27bf59b35d0169291_hq.gif', alt: 'Don\'t mind me, I\'m just passing by...'}
        %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNavAltMarkup", "data-bs-toggle" => "collapse", :type => "button"}
          %img{src: 'https://icongr.am/clarity/bars.svg?size=30&color=ffffff'}
        #navbarNavAltMarkup.collapse.navbar-collapse{style: "justify-content: right"}
          .navbar-nav
            = link_to "Cobranças", billings_path, class: 'nav-link'
            = link_to "Cobranças do dia", billings_of_the_day_path, class: 'nav-link'
            = link_to "Clientes", clients_path, class: 'nav-link'
            = link_to "Métodos de pagamento", payment_methods_path, class: 'nav-link'
    .content
      = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BillingProject
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .content
      = yield